### ISSUE TITLE
Add support for fetching name by UUID (using Name History API)

### ISSUE THREAD

**Issue by Byteflux** [EngineHub/SquirrelID#5]
Previously this would have been achieved by the skinblob API which has a 1 request per minute per UUID rate limit, however, the same can be achieved with the Name History API without the strict rate limit.

Since the API accepts a single UUID input, this would be used to fetch a profile containing the latest name. Something simple like: `Profile profile = resolver.findById(id)`

Name History API: http://wiki.vg/Mojang_API#UUID_-.3E_Name_history

**Comment by pavog** [comment]
I added this feature in [my fork](https://github.com/pavog/SquirrelID).
You can use it in maven via jitpack.io.

**Comment by me4502** [comment]
Published in 0.3.0
